package model;
// Generated 27-mar-2018 18:42:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Jugada generated by hbm2java
 */
public class Jugada  implements java.io.Serializable {


     private int id;
     private Animal animal;
     private Sorteo sorteo;
     private Ticket ticket;
     private Usuario usuario;
     private BigDecimal monto;

    public Jugada() {
    }

    public Jugada(int id, Animal animal, Sorteo sorteo, Ticket ticket, Usuario usuario, BigDecimal monto) {
       this.id = id;
       this.animal = animal;
       this.sorteo = sorteo;
       this.ticket = ticket;
       this.usuario = usuario;
       this.monto = monto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public Sorteo getSorteo() {
        return this.sorteo;
    }
    
    public void setSorteo(Sorteo sorteo) {
        this.sorteo = sorteo;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


