package model;
// Generated 27-mar-2018 18:42:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String serial;
     private Date fecha;
     private Date hora;
     private String ip;
     private BigDecimal total;
     private Set jugadas = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(int id, Usuario usuario, String serial, Date fecha, Date hora, String ip) {
        this.id = id;
        this.usuario = usuario;
        this.serial = serial;
        this.fecha = fecha;
        this.hora = hora;
        this.ip = ip;
    }
    public Ticket(int id, Usuario usuario, String serial, Date fecha, Date hora, String ip, BigDecimal total, Set jugadas) {
       this.id = id;
       this.usuario = usuario;
       this.serial = serial;
       this.fecha = fecha;
       this.hora = hora;
       this.ip = ip;
       this.total = total;
       this.jugadas = jugadas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set getJugadas() {
        return this.jugadas;
    }
    
    public void setJugadas(Set jugadas) {
        this.jugadas = jugadas;
    }




}


