package model;
// Generated 27-mar-2018 18:42:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String username;
     private String pass;
     private String nombreApellido;
     private int rol;
     private String telefono;
     private Set tickets = new HashSet(0);
     private Set jugadas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String username, String pass, String nombreApellido, int rol) {
        this.id = id;
        this.username = username;
        this.pass = pass;
        this.nombreApellido = nombreApellido;
        this.rol = rol;
    }
    public Usuario(int id, String username, String pass, String nombreApellido, int rol, String telefono, Set tickets, Set jugadas) {
       this.id = id;
       this.username = username;
       this.pass = pass;
       this.nombreApellido = nombreApellido;
       this.rol = rol;
       this.telefono = telefono;
       this.tickets = tickets;
       this.jugadas = jugadas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getNombreApellido() {
        return this.nombreApellido;
    }
    
    public void setNombreApellido(String nombreApellido) {
        this.nombreApellido = nombreApellido;
    }
    public int getRol() {
        return this.rol;
    }
    
    public void setRol(int rol) {
        this.rol = rol;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getJugadas() {
        return this.jugadas;
    }
    
    public void setJugadas(Set jugadas) {
        this.jugadas = jugadas;
    }




}


